mkdir build
cd build
export BOOST_ROOT=$PREFIX

cmake .. -DWALBERLA_BUILD_WITH_PYTHON=ON -DWALBERLA_BUILD_WITH_PYTHON_MODULE=ON -DWALBERLA_BUILD_WITH_OPENMESH=ON

make -j ${CPU_COUNT} pythonModuleInstall
